Repository panoptes-organization/panoptes, pull requests merged in 2020-11, with the labels that each got.

#86 Quick fix: Separate pypi installation from source code insatllation
  README.md
Labels: documentation

#106 Fix the number of workflows reported on the front page
  panoptes/static/src/index.html
Labels: bug, enhancement, python

#108 Make colors consistent between workflows and jobs
  panoptes/static/src/job.html
  panoptes/static/src/workflow.html
Labels: bug, enhancement, python

#110 add check if the wf is running. if running reject the deletion
  panoptes/routes/api.py
  panoptes/server_utilities/db_queries.py
Labels: database, python

#112 Feature/111 clean up whole database
  panoptes/routes/api.py
  panoptes/server_utilities/db_queries.py
Labels: database, python

#124 Add API documentation in README.md. Update contributors. Fixes #117
  README.md
  contributors.md
Labels: documentation
