Repository panoptes-organization/panoptes, pull requests merged in 2020-12, with the labels that each got.

#129 Feature/128 full crud operation
  .travis.yml
  README.md
  panoptes/routes/api.py
  panoptes/server_utilities/db_queries.py
  panoptes/tests/api_test.py
Labels: database, dependencies, docker, python

#132 Bug in test test_specific_work_flow_all_jobs_valid #131
  panoptes/tests/api_test.py
Labels: blocked, bug

#140 feature/10 Clean up DB button
  panoptes/static/src/css/style.css
  panoptes/static/src/index.html
  panoptes/static/src/job.html
  panoptes/static/src/js/src/init.js
  panoptes/static/src/searchResults.html
  panoptes/static/src/workflow.html
  panoptes/static/src/workflows.html
Labels: enhancement
